=== idno237/BulletinXML/ecole.dtd
<!ELEMENT ecole (membres_administratifs, classes, matieres, emploi_du_temps)>

<!ELEMENT membres_administratifs (proviseur, proviseur_adjoint, censeur, intendant, cpe, secretaire, surveillants)>
<!ELEMENT proviseur (#PCDATA)>
<!ELEMENT proviseur_adjoint (#PCDATA)>
<!ELEMENT censeur (#PCDATA)>
<!ELEMENT intendant (#PCDATA)>
<!ELEMENT cpe (#PCDATA)>
<!ELEMENT secretaire (#PCDATA)>
<!ELEMENT surveillants (surveillant+)>
<!ELEMENT surveillant (#PCDATA)>

<!ELEMENT classes (classe+)>
<!ELEMENT classe (professeur_principal, eleves, moyenne_generale)>
<!ATTLIST classe identifiant ID #REQUIRED>
<!ELEMENT professeur_principal (#PCDATA)>
<!ELEMENT eleves (eleve+)>
<!ELEMENT eleve (nom, prenom, identifiant_unique, matieres, moyenne)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT identifiant_unique (#PCDATA)>
<!ELEMENT matieres (matiere+)>
<!ELEMENT matiere (nom, notes)>
<!ELEMENT notes (note+)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT moyenne (#PCDATA)>
<!ELEMENT moyenne_generale (#PCDATA)>

<!ELEMENT matieres (matiere+)>
<!ELEMENT matiere (nom, professeur_enseignant)>
<!ATTLIST matiere identifiant ID #REQUIRED>
<!ELEMENT professeur_enseignant (#PCDATA)>

<!ELEMENT emploi_du_temps (jour+)>
<!ELEMENT jour (cours+)>
<!ATTLIST jour date CDATA #REQUIRED>
<!ELEMENT cours (heure_debut, heure_fin, classe_concernee)>
<!ATTLIST cours identifiant_matiere IDREF #REQUIRED>
<!ATTLIST cours heure_debut CDATA #REQUIRED>
<!ATTLIST cours heure_fin CDATA #REQUIRED>
<!ATTLIST cours classe_concernee CDATA #REQUIRED>

=== idno237/BulletinXML/ecole.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="bulletin.xsl"?>
<!DOCTYPE ecole SYSTEM "ecole.dtd">
<ecole>
  <!-- Informations sur les membres administratifs -->
  <membres_administratifs>
    <proviseur>Nguémo</proviseur>
    <proviseur_adjoint>Mbella</proviseur_adjoint>
    <censeur>Fomukong</censeur>
    <intendant>Ngounou</intendant>
    <cpe>Tchinda</cpe>
    <secretaire>Yonkeu</secretaire>
    <surveillants>
      <surveillant>Biyong</surveillant>
      <surveillant>Kenfack</surveillant>
    </surveillants>
  </membres_administratifs>

  <!-- Informations sur les classes -->
  <classes>
    <classe identifiant="6eme"> 
    <nom>6eme</nom>
      <professeur_principal>Madame Manga</professeur_principal>
      <eleves>
        <!-- Premier élève -->
        <eleve>
          <nom>Nkemayang</nom>
          <prenom>Paul</prenom>
          <identifiant_unique>001</identifiant_unique>
          <!-- Matières enseignées avec les notes -->
          <matieres>
            <matiere>
              <nom>Français</nom>
              <notes>
                <note>14</note>
              </notes>
            </matiere>
              <matiere>
                  <nom>Anglais</nom>
                  <notes>
                      <note>18</note>
                  </notes>
              </matiere>
              <!-- Ajout les autres matières enseignées avec les notes -->
              <matiere>
                  <nom>Maths</nom>
                  <notes>
                      <note>16</note>
                  </notes>
              </matiere>
              <matiere>
                  <nom>PCT</nom>
                  <notes>
                      <note>18</note>
                  </notes>
              </matiere>
            <!-- Ajout les autres matières enseignées avec les notes -->
          </matieres>
          <moyenne>16.5</moyenne>
        </eleve>        
        <!-- Ajout les autres élèves de la classe de 6ème -->
        <!-- Deuxième élève -->
        <eleve>
          <nom>Fouda</nom>
          <prenom>Marie</prenom>
          <identifiant_unique>002</identifiant_unique>
          <!-- Matières enseignées avec les notes -->
          <matieres>
            <matiere>
              <nom>Français</nom>
              <notes>
                <note>15</note>
              </notes>
            </matiere>
              <matiere>
                  <nom>Anglais</nom>
                  <notes>
                      <note>18</note>
                  </notes>
              </matiere>
              <!-- Ajout les autres matières enseignées avec les notes -->
              <matiere>
                  <nom>Maths</nom>
                  <notes>
                      <note>06</note>
                  </notes>
              </matiere>
              <matiere>
                  <nom>PCT</nom>
                  <notes>
                      <note>08</note>
                  </notes>
              </matiere>
            <!-- Ajout les autres matières enseignées avec les notes -->
          </matieres>
          <moyenne>11.75</moyenne>
        </eleve>
        <!-- Ajout les autres élèves de la classe de 6ème -->
      </eleves>
      <moyenne_generale>13</moyenne_generale>
    </classe>


    <classe identifiant="5eme">
        <nom>5eme</nom>
        <professeur_principal>Mme. Ngounou</professeur_principal>
        <!-- Liste d'élèves -->
        <eleves>
            <eleve>
                <nom>Mbia</nom>
                <prenom>Pierre</prenom>
                <identifiant_unique>003</identifiant_unique>
                <!-- Matières enseignées avec les notes -->
                <matieres>
                    <matiere>
                        <nom>Français</nom>
                        <notes>
                            <note>12</note>
                        </notes>
                    </matiere>
                    <matiere>
                        <nom>Anglais</nom>
                        <notes>
                            <note>14</note>
                        </notes>
                    </matiere>
                    <!-- Ajout les autres matières enseignées avec les notes -->
                    <matiere>
                        <nom>Maths</nom>
                        <notes>
                            <note>16</note>
                        </notes>
                    </matiere>
                    <matiere>
                        <nom>Physique</nom>
                        <notes>
                            <note>13</note>
                        </notes>
                    </matiere>
                    <!-- identique pour les autres matières -->
                </matieres>
                <moyenne>14.75</moyenne>
            </eleve>
            <eleve>
                <nom>Mbiapie oba</nom>
                <prenom>Pierre</prenom>
                <identifiant_unique>0033</identifiant_unique>
                <!-- Matières enseignées avec les notes -->
                <matieres>
                    <matiere>
                        <nom>Français</nom>
                        <notes>
                            <note>12</note>
                        </notes>
                    </matiere>
                    <matiere>
                        <nom>Anglais</nom>
                        <notes>
                            <note>18</note>
                        </notes>
                    </matiere>
                    <!-- Ajout les autres matières enseignées avec les notes -->
                    <matiere>
                        <nom>Maths</nom>
                        <notes>
                            <note>16</note>
                        </notes>
                    </matiere>
                    <matiere>
                        <nom>Physique</nom>
                        <notes>
                            <note>18</note>
                        </notes>
                    </matiere>
                    <!-- identique pour les autres matières -->
                </matieres>
                <moyenne>16</moyenne>
            </eleve>
            <!-- Ajout les autres élèves -->
        </eleves>
        <moyenne_generale>15.35</moyenne_generale>
    </classe>
    
    <classe identifiant="4eme">
        <nom>4eme</nom>
        <professeur_principal>M. Fomukong</professeur_principal>
        <!-- Liste d'élèves -->
        <eleves>
            <eleve>
                <nom>Biyong samuel</nom>
                <prenom>Samuel</prenom>
                <identifiant_unique>003</identifiant_unique>
                <!-- Matières enseignées avec les notes -->
                <matieres>
                    <matiere>
                        <nom>Français</nom>
                        <notes>
                            <note>12</note>
                        </notes>
                    </matiere>
                    <matiere>
                        <nom>Maths</nom>
                        <notes>
                            <note>15</note>
                        </notes>
                    </matiere>
                    <!-- Ajout les autres matières enseignées avec les notes -->
                    
                    <matiere>
                        <nom>Histoire</nom>
                        <notes>
                            <note>14</note>
                        </notes>
                    </matiere>
                    <matiere>
                        <nom>Géographie</nom>
                        <notes>
                            <note>16</note>
                        </notes>
                    </matiere>
                    <!-- Ajout les autres matières avec les notes -->
                </matieres>
                <moyenne>14.25</moyenne>
            </eleve>
            <eleve>
                <nom>Fonu eniel</nom>
                <prenom>Sam</prenom>
                <identifiant_unique>004</identifiant_unique>
                <!-- Matières enseignées avec les notes -->
                <matieres>
                    <matiere>
                        <nom>Français</nom>
                        <notes>
                            <note>02</note>
                        </notes>
                    </matiere>
                    <matiere>
                        <nom>Maths</nom>
                        <notes>
                            <note>15</note>
                        </notes>
                    </matiere>
                    <!-- Ajout les autres matières enseignées avec les notes -->
             
                    <matiere>
                        <nom>Histoire</nom>
                        <notes>
                            <note>10</note>
                        </notes>
                    </matiere>
                    <matiere>
                        <nom>Géographie</nom>
                        <notes>
                            <note>08</note>
                        </notes>
                    </matiere>
                    <!-- Ajout les autres matières avec les notes -->
                </matieres>
                <moyenne>8.75</moyenne>
            </eleve>
            
            <!-- Ajout les autres élèves de la classe de 4ème -->
        </eleves>
        <moyenne_generale>11.25</moyenne_generale>
    </classe>
    
    <classe identifiant="3eme">
        <nom>3eme</nom>
        <professeur_principal>M. Ekotto</professeur_principal>
        <!-- Liste d'élèves -->
        <eleves>
            <eleve>
                <nom>Ekotto dav</nom>
                <prenom>David</prenom>
                <identifiant_unique>004</identifiant_unique>
                <!-- Matières enseignées avec les notes -->
                <matieres>
                    <matiere>
                        <nom>Français</nom>
                        <notes>
                            <note>13</note>
                        </notes>
                    </matiere>
                    <matiere>
                        <nom>Maths</nom>
